apiVersion: apps/v1
kind: Deployment
metadata:
  name: swotweb
spec:
  revisionHistoryLimit: 2
  replicas: 2
  selector:
    matchLabels:
      app: swotweb
  template:
    metadata:
      labels:
        app: swotweb
    spec:
      containers:
        - name: swotweb
          image: docker.pkg.github.com/jb3/swot-backend/swot
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: swot-secrets
