name: Docker

on:
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: swot

jobs:
  test_docker_image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test build Docker image
        run: docker build . --file Dockerfile

  push_docker_image:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile -t j03b/swot-backend/swot:latest

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: j03b/swot-backend/swot
          username: j03b
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
